name: dev build
on:
  push:
    branches:
      - '**'        # matches every branch
jobs:
  build:
    name: dev build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: tune_neutral:latest
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18.0-beta1'
      - name: "run golang tests"
        run: go test ./...
        working-directory: ./backend 

